import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../styles/globals.css"
import Tanstackprovider from "@/providers/TanstackProvider"
import { SiteFooter } from "@/components/footer"
import SessionWrapper from "@/components/sessionWrapper"
import Header from "@/components/navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={`${inter.className} transition-colors duration-150`}
          suppressHydrationWarning={true}
        >
          <Header />
          <Tanstackprovider>
            <div className="my-2">{children}</div>
          </Tanstackprovider>
          <SiteFooter />
        </body>
      </html>
    </SessionWrapper>
  )
}
