import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../styles/globals.css"
import Tanstackprovider from "@/providers/TanstackProvider"
import SessionWrapper from "@/components/SessionWrapper"
import Header from "@/components/header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SessionWrapper>
      <html lang="en" className="light">
        <body className={inter.className} suppressHydrationWarning={true}>
          <Header />
          <Tanstackprovider>
            <div>{children}</div>
          </Tanstackprovider>
        </body>
      </html>
    </SessionWrapper>
  )
}
